name: Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.x

      - name: Install deps
        run: npm ci

      - name: Build dist/index.js
        run: npm run build

      - name: Check for dist/index.js
        run: test -f dist/index.js
