name: Build Check

on:
  pull_request:
    branches: [ main ]

permissions: {}

jobs:
  build:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.x

      - name: Install deps
        run: npm ci

      - name: Build dist/index.js
        run: npm run build

      - name: Check for dist/index.js
        run: test -f dist/index.js
